// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-04-09 21:31:52.064114498 -0300 -03 m=+0.027401836

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Tiago Carreira",
            "url": "https://github.com/tcarreira/superhero"
        },
        "license": {
            "name": "MIT License",
            "url": "https://raw.githubusercontent.com/tcarreira/superhero/master/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/super-hero": {
            "post": {
                "description": "Create new Super",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create new Super (hero/vilan)",
                "parameters": [
                    {
                        "description": "super hero name",
                        "name": "super",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.exampleSuperHeroVilanJSON"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Super was created",
                        "schema": {
                            "$ref": "#/definitions/main.Super"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.Super": {
            "type": "object",
            "properties": {
                "fullname": {
                    "type": "string",
                    "example": "SuperHero1's Full Name"
                },
                "groups": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "image_url": {
                    "type": "string",
                    "example": "https://http.cat/200"
                },
                "intelligence": {
                    "type": "integer",
                    "example": 90
                },
                "name": {
                    "type": "string",
                    "example": "SuperHero1"
                },
                "occupation": {
                    "type": "string",
                    "example": "Programmer"
                },
                "power": {
                    "type": "integer",
                    "example": 80
                },
                "relatives_count": {
                    "type": "integer"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "HERO",
                        "VILAN"
                    ],
                    "example": "HERO"
                },
                "uuid": {
                    "type": "string",
                    "example": "47c0df01-a47d-497f-808d-181021f01c76"
                }
            }
        },
        "main.exampleSuperHeroVilanJSON": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "name1"
                },
                "type": {
                    "type": "string",
                    "example": "HERO"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "Superhero API",
	Description: "SuperHero API - Go (inspired by superheroapi.com) \\n This is being made in the context of https://github.com/levpay/careers#desafio",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
